apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tcp-echo-server
  namespace: tcp-echo
spec:
  patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tcp-echo-server
      spec:
        template:
          spec:
            containers:
              - name: tcp-echo-container
                image: andrescaroc/tcp-echo-server:v0.1.7
