apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tcp-echo
resources:
  - ../../base/tcp-echo
patches:
  - path: deploy-patch.yaml
    target:
      kind: Deployment
      name: tcp-echo-server
