apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 2m0s
  wait: true
  timeout: 3m0s
  prune: true
  force: false
  path: ./infrastructure/staging
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
