---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m
  timeout: 3m0s
  wait: true
  prune: true
  force: false
  path: ./infrastructure/controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  wait: true
  prune: true
  force: false
  path: ./infrastructure/configs
  sourceRef:
    kind: GitRepository
    name: flux-system
